version: 2.1

jobs:
  reconstruct_circle_compare_url:
    resource_class: small
    docker:
      - image: circleci/python:buster
    working_directory: ~/project
    environment:
      MASTER_BRANCH: master
      CIRCLE_COMPARE_URL_DEBUG: true
    steps:
      - checkout
      - run:
          name: Reconstruct Circle Compare URL
          command: |
            set -o errexit
            ./reconstruct_circle_compare_url.sh
            cat GIT_DIFF_OUT.txt

workflows:
  version: 2
  test_flow:
    jobs:
      - reconstruct_circle_compare_url
