version: 2.1

orbs:
  slack: circleci/slack@3.4.1

jobs:
  notify_me:
    resource_class: small
    docker:
      - image: circleci/python:buster
    working_directory: ~/project
    environment:
      PUSHED: ""
    steps:
      - checkout

      - run:
          name: Generate environment variable
          command: |
            set -o errexit
            ./generate_env_var.sh
            PUSHED=$(cat PUSHED)

      - slack/notify:
          channel: "random"
          message: "Something got update: ${PUSHED}"



workflows:
  version: 2
  test_flow:
    jobs:
      - notify_me
